### ISSUE TITLE
when "Declare exceptions thrown by tested class" setting is on - test code exceptions should be taken into account

### ISSUE THREAD

**Issue by yaronyam** [wrdv/testme-idea#32]
When Setting "Declare exceptions thrown by tested class" is set  and no exception declared by tested method - still need to consider exceptions declared by test code methods
For instance, this Powermock SDK method - org.powermock.api.mockito.expectation.PowerMockitoStubber#when(T, java.lang.String, java.lang.Object...)  - declares an exception

![image](https://github.com/wrdv/testme-idea/assets/10505445/79430c50-cefc-486f-bc1f-25bd8b52bca6)

can be tested with com.weirddev.testme.intellij.generator.TestMeGeneratorJunit4PowerMockTest#testRenderInternalMethodCallStubs
we probably need to add some logic in Mock builder to decide if throws Exception should be declared even though tested method does not.

related to https://github.com/wrdv/testme-idea/pull/29
FYI @zhangfj88

**Comment by zhangfj88** [comment]
Thank you for raising the issue and suggestions regarding this feature. I will submit the revised code accordingly.

**Comment by yaronyam** [comment]
Fixed in #34. Released in [V6.4.1](https://plugins.jetbrains.com/plugin/9471-testme/versions/stable/530670) Thanks again for fixing this @zhangfj88
