### ISSUE TITLE
Improving CONTRIBUTING.md for Generating Proper JAR File

### ISSUE THREAD

**Issue by karlmatti** [wrdv/testme-idea#33]
Hi there,

I've been using this plugin for a few months and now I want to contribute to the project. But, I'm stuck trying to build the right JAR file needed for local use. Can someone please update the `CONTRIBUTING.md` file to explain how to do this?

Right now, the instructions say to run a task called `runIdea`, but it doesn't exist. The closest thing I found is `runIde`, but I'm not sure if that's what I need because I just want to create the JAR file, not download a new version of IntelliJ.

There's also a task called `buildNeeded` which seems close to what I need, but it needs some extra stuff like `META-INF` to be a working version.

Thanks for any help you can provide!

**Comment by yaronyam** [comment]
Thanks for the valuable feedback,
project is using gradle tasks provided by [intellij-platform-gradle-plugin](https://github.com/JetBrains/intellij-platform-gradle-plugin) as referenced in CONTRIBUTING.md .
_intellij-platform-gradle-plugin_ has renamed _runIdea_ task to _runIde_ - I've updated [CONTRIBUTING.md](https://github.com/wrdv/testme-idea/blob/master/CONTRIBUTING.md) to reflect that. hope it's better now.
Plugin installation artifact is created by `buildPlugin` task - I rarely use it. `runIde` is more convenient for manually testing IntelliJ with installed plugin

**Comment by huangliang992** [comment]
maybe we should add the jdk and gradle version in the readMe, jdk 17 is needed.

**Comment by yaronyam** [comment]
@huangliang992  - updated CONTRIBUTING.md with references to Gradle & JDK versions - https://github.com/wrdv/testme-idea/commit/0da084b155d295fc8bcaf6f0524619d3a0f5ae97. hope it helps. thanks for the feedback

**Comment by karlmatti** [comment]
Thanks, this resolved my issue!
