### ISSUE TITLE
Prioritize Custom Templates in Template Selection

### ISSUE THREAD

**Issue by karlmatti** [wrdv/testme-idea#35]
I propose prioritizing custom templates over default ones in the template selection process within the plugin. Currently, when creating a test for a .java class, the available templates are listed with default ones appearing first, followed by custom templates. This arrangement necessitates an additional step to select frequently used custom templates from the bottom of the list.

By reordering the sorting so that custom templates appear first, users can quickly access their preferred templates without the need for extra navigation. This adjustment would streamline the template selection process and enhance user efficiency.

I am prepared to implement this change and submit a pull request upon approval.

**Comment by yaronyam** [comment]
ok. I think it would be good to introduce sorting controls ⬆️ ⬇️ in template setting to set the order . If that's too much of an effort, then yes, defaulting the custom templates first sounds good for now.

BTW, the test template selection popup supports search as you type. I usually type 1 - 3 letters to locate the relevant template and hit enter.
Thanks for raising this issue with the willingness to contribute!

**Comment by karlmatti** [comment]
Adding sorting controls sounds like a good idea. Currently, sorting seems effective. Searching for a template requires about the same effort as scrolling to the end of the list when there's only one template. I'm not sure how most users utilize the plugin, but reordering would already improve efficiency for me. I'll consider adding sorting controls but will not make any promises yet.

Can I get contribution rights so I could raise a pull request?

**Comment by karlmatti** [comment]
Issue still open

**Comment by yaronyam** [comment]
@karlmatti cool 👍  any github user should be able to raise a PR. please let me know if you bump into issues. thanks

**Comment by yaronyam** [comment]
Closed by #36 released in [V6.4.1](https://plugins.jetbrains.com/plugin/9471-testme/versions/stable/530670) Thanks for contributing
