### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2024.2.0.1)

### ISSUE THREAD

**Issue by sycho-c** [wrdv/testme-idea#47]
Not compatible with the version of your running IDE (IntelliJ IDEA 2024.2.0.1)

**Comment by yaronyam** [comment]
Thanks for raising this issue, it's probably the highest priority, but might take some time... I don't have the capacity to work on it anytime soon.... related to #41

**Comment by yaronyam** [comment]
Support for IDEA 2024.2 developed by @huangliang992  in https://github.com/wrdv/testme-idea/pull/48  - released in [v7.6.0](https://plugins.jetbrains.com/plugin/9471-testme/versions/stable/603910)

**Comment by sycho-c** [comment]
@yaronyam Thank you for resolving this issue so quickly! Your help is greatly appreciated.
